providers = []

[phases.setup]
nixPkgs = ["bun", "ffmpeg", "nodejs_20"]

[phases.install]
cmd = "bun install --frozen-lockfile"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "NODE_PATH=/app/node_modules:/app/packages/backend/node_modules bun run packages/backend/src/index.ts"