providers = []

[phases.setup]
nixPkgs = ["bun", "ffmpeg", "nodejs_20"]

[phases.install]
cmd = "rm -f pnpm-lock.yaml && bun install --frozen-lockfile"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "cd /app/packages/backend && bun run src/index.ts"