providers = []

[phases.setup]
nixPkgs = ["bun", "ffmpeg"]

[phases.install]
cmd = "bun install --frozen-lockfile"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "bun run packages/backend/src/index.ts"