providers = []

[phases.setup]
nixPkgs = ["bun", "ffmpeg", "vips", "pkg-config", "nodejs_20"]

[phases.install]
cmd = "bun install --frozen-lockfile && npm rebuild sharp"

[phases.build]
cmd = "echo 'Build complete'"

[start]
cmd = "bun run packages/backend/src/index.ts"