[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "bun run packages/backend/src/index.ts"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Disable nixpacks completely and force Docker
[variables]
RAILWAY_DOCKERFILE_PATH = "Dockerfile"
NIXPACKS_NO_DEFAULT_PROVIDERS = "true"
DISABLE_NIXPACKS = "true" 